--  Create a database named vet_clinic
CREATE DATABASE vet_clinic;

-- Create a table named animals with the following columns:
CREATE TABLE animals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    date_of_birth DATE,
    escape_attempts INTEGER,
    neutered BOOLEAN,
    weight_kg DECIMAL,
    PRIMARY KEY(id)
);

-- Add a column species of type string to animals table
ALTER TABLE animals
ADD species VARCHAR(100);
