CREATE DATABASE medical_clinic

CREATE TABLE medical_histories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  admitted_at TIMESTAMP,
  patient_id INTEGER,
  status VARCHAR(150),
  PRIMARY KEY (id),
  FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
  FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
  FOREIGN KEY (treatment_id) REFERENCES treatments(id) ON DELETE CASCADE
);

CREATE TABLE patients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(150),
  date_of_birth DATE
);

