--  Create a database named vet_clinic
CREATE DATABASE vet_clinic;

-- Create a table named animals with the following columns:
CREATE TABLE animals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    date_of_birth DATE,
    escape_attempts INTEGER,
    neutered BOOLEAN,
    weight_kg DECIMAL,
    PRIMARY KEY(id)
);

-- Add a column species of type string to animals table
ALTER TABLE animals
ADD species VARCHAR(100);

--  Create owners table
CREATE TABLE owners (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(100),
    age INTEGER,
    PRIMARY KEY(id)
);

-- Create Species table
CREATE TABLE species (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    PRIMARY KEY(id)
);

-- Remove species column from animals table
ALTER TABLE animals
DROP COLUMN species;


-- Add species_id column to animals table
ALTER TABLE animals
ADD COLUMN species_id INTEGER REFERENCES species(id);

-- Add owner_id column to animals table
ALTER TABLE animals
ADD COLUMN owner_id INTEGER REFERENCES owners(id);